### ISSUE TITLE
Issues Version 1

### ISSUE THREAD

**Issue by NextGenerationHackers** [SCRIPT-KIDDYS/WarCommander-Decode-Strings#1]
Here are a Few Issues We Would like Fixed:

1. Ask For Location of The Scripts instead of drag and drop.
2. Ask the user where to place the Decoded Scripts.
~~3. Make the Code Updates Auto Update. If any of these can work:
	A. Ask User to Input the Latest Version: class_2.method_6, class_2.method_7... etc
	B. Auto-Detect latest Version by first reading 1 of the Scripts and then apply the latest Version.
	C. Make a Asterisk type of function, to where it auto reads every time... For Example: class_2.method*~~
4. Make a .exe Version.
~~5. Fix Index was out of range error when using the latest and the full WC scripts. Latest is: class_2.method_6.~~

**Comment by Fluffer-Nutter** [comment]
1. Drag and Drop will work. If i can think of an easy way to ask for location ill add that also.
2. Same as 1.
3. Option C would work the best with Regex
4. Never gonna happen. If it was an EXE then noobs would use it. This project was ment for smarter people.
5 Check.

ETA : Monday (3-25-2019)
