### ISSUE TITLE
BROKEN AT THE MOMENT!

### ISSUE THREAD

**Issue by Fluffer-Nutter** [SCRIPT-KIDDYS/WarCommander-Decode-Strings#3]
Sill new to pull requests on GitHub. So i might have merged into master branch. OOPS. Use this commit for a working version.

https://github.com/SCRIPT-KIDDYS/WarCommander-Decode-Strings/tree/3da2b0d9fb37ea5a56f3031263dca73b7d13bd83

**Comment by NextGenerationHackers** [comment]
I don't understand lol mainly because i don't understand github that well.

**Comment by xbud** [comment]
GJ Jimmy, we showed you string decode 2 years ago why release this now?  Just curious, makes no difference anymore.

**Comment by Fluffer-Nutter** [comment]
@xbud A "video" was shown to me, nothing else. Decided to open source it so others can also use it. Game is pretty much dead for hacks so now it should just be public information. I talked with DiDi and let him know ahead of time.

**Comment by xbud** [comment]
No you were given a zip file with the numbers changed to strings, the strings were inside the method that changes the numbers to strings.  My four year old could have figured it out if I gave him what we gave you.

**Comment by Fluffer-Nutter** [comment]
@xbud Given a 1 time zip file is a little different then being able to do it each update. I appreciate the comments tho. Glad to see your 4 year old is hacking also. Stay safe.
